In [12]:
#solution
x = str(input("What is the input string? "))

while x== "":
    print("Please enter your name")
    x = str(input("What is the input string? "))


print(f"{x} has {len(x)} characters")

What is the input string? 
Please enter your name
What is the input string? 
Please enter your name
What is the input string? Julio
Julio has 5 characters


In [13]:
def printing_quotes():
    x=input("What is the quote? ")
    y=input("Who said that?")
    print(y+" said:"+x)

In [14]:
printing_quotes()

What is the quote? El hombre es producto de sus pensamientos
Who said that?Gandhi
Gandhi said:El hombre es producto de sus pensamientos


In [15]:
#solution:
noun = input("Enter a noun? ")
verb = input("Enter a verb? ")
adjective = input("Enter an adjective? ")
adverb = input("Enter an averb? ")

print(f"Do you {verb} your {adjective} {noun} {adverb}?. That's hilarious!")

Enter a noun? a
Enter a verb? a
Enter an adjective? a
Enter an averb? a
Do you a your a a a?. That's hilarious!


In [32]:
first=input("first number? ")
second=input("second? ")
ff=float(first)
sf=float(second)
def solving():
    print(ff+sf)
    print(ff-sf)
    print(ff*sf)
    print(ff/sf)
    
solving()

first number? 3
second? 1
4.0
2.0
3.0
3.0


In [43]:
#solution:
x = int(input("What is the first number? "))
y = int(input("What is the second number? "))

print (f"{x} + {y} =",x+y)
print (f"{x} - {y} =",x-y)
print (f"{x}*{y} =",x*y)
print (f"{x}/{y} =",round(x/y,2))

What is the first number? 3
What is the second number? 1
3 + 1 = 4
3 - 1 = 2
3*1 = 3
3/1 = 3.0


In [144]:
from datetime import date

In [145]:
date.today()

datetime.date(2020, 4, 10)

In [165]:
age=int(input("what is your age? "))
retirement=int(input("desired age to retire? "))
print(f"You have {retirement-age} years to retire")
print(f"it is {date.today()}, you will retire in {2020+age}")

what is your age? 20
desired age to retire? 60
You have 40 years to retire
it is 2020-04-10, you will retire in 2040


In [154]:
import time
import datetime

In [155]:
print(dir(datetime))

['MAXYEAR', 'MINYEAR', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'date', 'datetime', 'datetime_CAPI', 'sys', 'time', 'timedelta', 'timezone', 'tzinfo']


In [173]:
t1 = date.today()
t2 = date(year = 2020+age,month=1,day=1)
t3 = t1 - t2
print(t3)

-7205 days, 0:00:00


In [174]:
print(t2)

2040-01-01


In [192]:
#ex.7
length=float(input("length? "))
width=float(input("width? "))
print(f"you entered {length} as length and {width} as width")
a=input("is it correct? ")
if a=="yes":
    b=length*width
    d=0.0921
    c=b*d
    print(f"the area is: {b} square feet")
    print(f"the area is: {c} square meters")
else:
    print("error")
        

length? 15
width? 20
you entered 15.0 as length and 20.0 as width
is it correct? yes
the area is: 300.0 square feet
the area is: 27.63 square meters


In [27]:
p=int(input("How many people? "))
z=int(input("How many pizzas? "))

print(f'there are {p} people and {z} pizzas')

slices=z*4
x=slices/p

if x%2==0 or x==1:
    print(f'each person gets {x} slices of pizza')
    print(f'there are 0 leftover')

else: 
    y=round(x,0)
    print(f'each person gets {y} slices')
    print(f'there are leftovers')
    

    

How many people? 3
How many pizzas? 5
there are 3 people and 5 pizzas
each person gets 7.0 slices
there are leftovers


In [29]:
#solution ex. 8:
import math
X = False 
while X != True: 
    try:  
        people = float(input("How many people are you? "))
        pizza = float(input("How many pizza do you have? "))
        X = True 
    except ValueError:
        print('Non-numeric data found in the file. \n Please enter them in again?')
        X = False 
        
num = pizza*8
each = math.trunc(num/people) 
left = num%people 
print(f"{people} people and {pizza} pizzas")
print(f"Each person gets {each} pieces of pizza.")
print(f"There are {left} leftovers pieces")

How many people are you? 1
How many pizza do you have? 1
1.0 people and 1.0 pizzas
Each person gets 8 pieces of pizza.
There are 0.0 leftovers pieces


In [36]:
import math

x=int(input("What is the ceiling square foot?: "))
q=x/350
print(f'you will need to purchase {math.ceil(q)} gallons of paint \nto cover {x} square feets')

What is the ceiling square foot?: 8000
you will need to purchase 23 gallons of paint 
to cover 8000 square feets


In [47]:
#solution
room = input("Is the room round or rec? " )

if room == 'rec':
    x = False 
    while x == False:
        try: 
            l = float(input("Lenght of roof? "))
            w = float(input("Width of roof? "))
            x = True
        except ValueError:
            print("Enter a number > ")
            x = False 
            

    area = l*w
    paint = math.ceil(area/360)
    print(f"You will need to purchase {paint}\ngallons of paint to cover {area} square feet")
  
    
if room == 'round':
    x = False 
    while x == False:
        try: 
            r = float(input("Radius of roof? "))
            x = True
        except ValueError:
            print("Enter a number > ")
            x = False 
    area = math.pi*r**2
    paint = math.ceil(area/360) 
    print(f"You will need to purchase {paint}\ngallons of paint to cover {area} squre feet")


Is the room round or rec? rec
Lenght of roof? 0.5
Width of roof? 0.5
You will need to purchase 1
gallons of paint to cover 0.25 squre feet


In [4]:
tax=0.055
p1=float(input("Enter the price of the item: "))
q1=float(input("Enter the quantity of the item: "))
p2=float(input("Enter the price of the item 2: "))
q2=float(input("Enter the quantity of the item 2: "))
p3=float(input("Enter the price of the item 3: "))
q3=float(input("Enter the quantity of the item 3: "))
subtotal=round((p1*q1)+(p2*q2)+(p3*q3),2)
print(f'the subtotal is: {subtotal}$')
qtax=round(subtotal*tax,2)
print(f'tax is: {qtax}$')
print(f'the total is: {round(subtotal+qtax,2)}$')
    
    

Enter the price of the item: 3
Enter the quantity of the item: 4
Enter the price of the item 2: 6
Enter the quantity of the item 2: 2
Enter the price of the item 3: 9
Enter the quantity of the item 3: 8
the subtotal is: 96.0$
tax is: 5.28$
the total is: 101.28$


In [ ]:
## pro solution 10
num = input("Please input number of items? ")

Subtotal = 0
for i in range(1,int(num)+1):
    x = False
   
    while x == False:
        try: 
            price = float(input(f"Please enter the price of item {i}? "))
            quant = float(input(f"Please enter the quanity of item {i}?"))
            sub = price*quant
            x = True     
            Subtotal = Subtotal + sub 
        
        except ValueError:
            print("Enter a number > ")
            x = False 
tax = Subtotal*.055  
total = tax+Subtotal      
print(f"Subtotal: ${Subtotal}")
print(f"Tax: ${tax}")
print(f"Total: ${total}")

In [3]:
#11
Count = {"USA" : 1.187,"Bitcoin" : .0001, "Pound": .88}
cur = str(input("This is a euro conversion program. Pick the currency: USA, BITcoin or Pound "))

euro = float(input("How may euro's are you exchanging? "))

convert = round(float(Count[cur])*euro,2)
print(f"You have {convert} {cur}'s")

This is a euro conversion program. Pick the currency: USA, BITcoin or Pound USA
How may euro's are you exchanging? 10
You have 11.87 USA's


In [40]:
#simple interest
try:
    p0=float(input("Principal? "))
    r=float(input("Rate ? :"))
    t=float(input("Time? :"))
    total=round(p0*(1+(r/100)*t),2)
    print(f'Dear Sir, after {int(t)} years, the investment \nwill be worth {total}$')
except ValueError:
    print("Enter a valid number!!")

Principal? a
Enter a valid number!!


In [54]:
#solution
while True:
    try: 
        P = float(input("Enter principle? "))
        r = float(input("Enter the intrest rate? "))
        t = int(input("Enter the number of years? " ))
        break
    except ValueError:
        print("Enter a number")
    

for i in range(1, t+1):
    A = P*(1+(r/100)*i)
    print("After " + str(i) + " years " + str(round(A)))

    

Enter principle? 10
Enter the intrest rate? 5
Enter the number of years? 1
After 1 years 10


In [59]:
while True:
    try:
        p0=float(input("Principal? "))
        r=float(input("Rate ? :"))
        t=float(input("Time? :"))
        n=float(input("Times compounded?"))
        total=p0*(1+((r/100)/n)**(n*t))
        print(f'{round(p0,2)}$ invested at {r}% for {int(t)} years \ncompounded {n} times per year is {round(total,2)}')
        continue
    except ValueError:
        print("Enter a valid number!")

Principal? 10
Rate ? :5
Time? :2
Times compounded?2
10.0$ invested at 5.0% for 2 years 
compounded 2.0 times per year is 10.0
Principal? a
Enter a valid number!


KeyboardInterrupt: 

In [1]:
try:
    amount=float(input("$?: "))
    country=input("ESP or USA?: ")
    if country=="ESP" or "esp":
        total=amount*1.09
        tax=amount*0.09
        print(f'The subtotal is {amount}$\nThe tax is {round(tax,1)}$\nThe total is {round(total,2)}$')
    elif country=="USA" or "usa":
        total_1=amount*1.05
        tax_1=amount*0.05
        print(f'The subtotal is {amount}$\nThe tax is {round(tax_1,1)}$\nThe total is {round(total_1,2)}$')

except ValueError:
    print("error")

$?: 40
ESP or USA?: esp
The subtotal is 40.0$
The tax is 3.6$
The total is 43.6$


In [32]:
#solution
while True: 
    try: 
        a = float(input("What is the order amount? "))
        s = str(input("What is the state? "))
        break 
    except ValueError: 
        print("Enter a number >")
        
States = {'WI' : .055, 'MN' : .07}
tax = States[s]*a
print(tax)
print(tax+a)

What is the order amount? 10
What is the state? WI
0.55
10.55


In [33]:
import getpass

In [74]:
# 15
Passwords={"a":"hello","b":"hell","c":"hel"}
try:
    x = input("username a, b or c? ")
    y = getpass.getpass("What is the password? ")
    if x=="a":
        q=Passwords["a"]
        if y==q:
            print(f'Welcome, Sir {x}:)')
        else:
            print("wrong password")
    elif x=="b":
        w=Passwords["b"]
        if y==w:
            print(f'Welcome, Sir {x} :)')
        else:
            print("wrong password")
    elif x=="c":
        e=Passwords["c"]
        if y==e:
            print(f'Welcome, Sir {x} :)')
        else:
            print("wrong password")
    else:
        try:
            x=1+x
        except TypeError:
            print("Invalid username")
except ValueError:
    print("bye")

username a, b or c? a
What is the password? ········
Welcome, Sir a:)


In [4]:
#16
x=False
while x==False:
    try:
        age=float(input("What is your age? "))
        if age >= 16:
            print("You are legally able to drive")
            x=True
        elif age < 16:
            print("You are not legally able to drive")
            x=True
    except ValueError:
        print("Please, input a valid number")
        


What is your age? -1
You are not legally able to drive


In [13]:
#17
w=float(input("Weight?: "))
A=float(input("Alcohol consumed?: "))
r=input("man or woman?: ")
if r=="man":
    r=float(0.73)
elif r=="woman":
    r=float(0.66)
else:
    print("Enter 'man' or 'woman'")
H=float(input("Number of hours since last drink?"))
BAC=(A*5.14/w*r)-0.15*H
if BAC>0.08:
    print(f'Your BAC is {round(BAC,2)}\nIt is illegal to drive')
elif BAC<=0.08 and BAC>0:
    print(f'Your BAC is {round(BAC,2)}\nIt is legal to drive')
elif BAC<0:
    print("You entered the wrong numbers")
    

Weight?: 60
Alcohol consumed?: 1
man or woman?: man
Number of hours since last drink?1
You entered the wrong numbers


In [33]:
#18
x=False
while x==False:
    convert=input("Press C to convert from Fahrenheit to Celsius \nPress F to convert from Celsius to Fahrenheit")
    if convert=="c" or "C":
        c=float(input("Please enter the temperature in Fahrenheit"))
        conversion=(c-32)*5/9
        print(f'The temperatur in Celsius is {int(round(conversion,0))}')
    elif convert=="f" or "F":
        f=float(input("Please enter the temperature in Celsius"))
        conversion_1=(f*9/5)+32
        print(f'The temperatur in Fahrenheit is {int(round(conversion_1,0))}')
    else:
        print("Please enter correct inputs")

Press C to convert from Fahrenheit to Celsius 
Press F to convert from Celsius to Fahrenheitf
Please enter the temperature in Fahrenheit100
The temperatur in Celsius is 38


KeyboardInterrupt: 

In [52]:
#21
months={1:"January",2:"February",3:"March",4:"April",5:"May",6:"June"}

m=int(input("Which month?: "))
print(f'The name of the month is {months.get(m)}')

Which month?: 4
The name of the month is April


In [59]:
#22
a=float(input("Enter first number:"))
b=float(input("Enter second number:"))
c=float(input("Enter third number:"))

while True:
    if a==b or a==c or b==c:
        break
    else:
        if a>b and a>c:
            print(f'{int(round(a,0))} is the largest')
            break
        elif b>a and b>c:
            print(f'{int(round(b,0))} is the largest')
            break
        else:
            print(f'{int(round(c,0))} is the largest')
            break
    

Enter first number:3.6
Enter second number:1
Enter third number:2
4 is the largest


In [66]:
while True:
    a=float(input("Enter first number:"))
    b=float(input("Enter second number:"))
    c=float(input("Enter third number:"))
    if a==b or a==c or b==c:
        break
    else:
        print(f'{max(a,b,c)} is the largest')
        continue

Enter first number:1
Enter second number:2
Enter third number:3
3.0 is the largest
Enter first number:1
Enter second number:1
Enter third number:1


In [4]:
print("Answer with 'yes' or don't and press enter")
a=bool(input("Is the car silent?"))
if a==True:
    b=bool(input("Are the batteries corroed?:"))
    if b==True:
        print("Clean terminals")
    elif b==False:
        print("Replace cables")
elif a==False:
    c=bool(input("Does the car make a clicking noise?: "))
    if c==True:
        print("Replace the battery")
    elif c==False:
        d=bool(input("Does the car crank?"))
        if d==True:
            print("check spark")
        elif d==False:
            print("get out")

Answer with 'yes' or don't and press enter
Is the car silent?
Does the car make a clicking noise?: 
Does the car crank?yes
check spark


In [6]:
# 23
Actions = {'1': 'Is the car silent when turned on?',
         '2a': 'Are the Battery terminals corroded',
         '2b': 'Does the car make a clicking noise',
         '3a': 'Clean terminals',
         '3b': 'Replace cables',
         '3c': 'Replace battary',
         '3d': 'Does car crack',
         '4a': 'Check Spark plugs',
         '4c': 'Does engine start',
         '5a': 'Does your car have fuel',
         '6a': 'Check chock',
         '6b': 'Get it services'}

Steps = ['1','2a','2b','3a','3b','3c','3d','5a','6a','6b']

print(Actions['1'])

i = 1
while True:
    x = input('Y or N ')
    if x == 'Y': 
        print(Actions[Steps[i]])
        i = i + 1
    if x == 'N': 
        if i > 9:
            break
        
        print(Actions[Steps[i+1]])
        i = i + 2

Is the car silent when turned on?


KeyboardInterrupt: 

In [4]:
#chapter functions
#24
def anag_program():
    print("Enter two strings and I'll tell you\nif they are anagrams")
    s1=input("Enter first string: ")
    s2=input("Enter the second string")
    if sorted(s1)==sorted(s2):
        print(f'"{s1}" and "{s2}" are anagrams')
    elif sorted(s1)!=sorted(s2):
        print(f'"{s1}" and "{s2}" are not anagrams')
    else:
        raise ValueError

In [8]:
anag_program()

Enter two strings and I'll tell you
if they are anagrams
Enter first string: 1
Enter the second string2
"1" and "2" are not anagrams


In [40]:
def password_validator(password):
    if len(password)<8:
        x=False
        while x==False:
            number="1234567890"
            for i in password:
                if i in number:
                    x=True
                    print("Your password is very weak")
                else:
                    print("Your password is weak")
    elif len(password)>=8:
        x=False
        while x==False:
            symbol="!.,¡"
            letter="qwertyuiop"
            for i in password:
                if i in symbol==True:
                    print("Your password is very strong")
                    x=True
                elif i in letter:
                    print("Your password is normal")
                    x=True    

In [42]:
password_validator("!q119")

Your password is weak
Your password is weak
Your password is very weak
Your password is very weak
Your password is very weak


In [27]:
def password_validator(password):
    try:
        if len(password)<8:
            number="1234567890"
            for i in password:
                if i in number == True:
                    x=1
                else:
                    x=0
    finally:
        final={0:"weak",1:"very weak"}
        print(f'Your password is {final.get(x)}')
        x=0
        

In [30]:
password_validator("12")

Your password is weak


In [8]:
number=[1,2,3,4,5,6,7,8,9,0]
x=0
for number in "1abc1":
    x=x+1
    print(x)
    

1
2
3
4
5


In [13]:
import math
math.log(1,10)

0.0

In [34]:
#26
def payoff():
    APR=float(input("APR?:"))
    i=APR/365
    b=float(input("balance?: "))
    p=float(input("monthly payment you can do?: "))
    n=-1/30*math.log(1+b/p*(1-(1+i)**30))/math.log(1+i)
    print(f'It will take you {n} months to pay off this card')

In [38]:
def payoff(APR,b,p):
    i=APR/365
    n=-1/30*math.log(1+b/p*(1-(1+i)**30))/math.log(1+i)
    print(f'It will take you {n} months to pay off this card')

In [39]:
payoff(0.12,5000,100)

It will take you 69.38218057582237 months to pay off this card


In [43]:
#27

def isSymbol(name): 
    x = 0 
    symbol = "~`!@#$%^&*()_-+={}[]:>;',</?*-+"
    for i in name:
        if i in symbol:
           x += 1
    if x > 0: return True
    if x == 0: return False 
    
def isNum(name):
    x = 0
    symbol = "1234567890"
    for i in name:
        if i in symbol:
           x += 1
    if x > 0: return True
    if x == 0: return False 
    
def isAlph(name):
    x = 0
    symbol = "qwertyuiopasdfghjklzxcvbnmQWERTYUIOPASDFGHJKLZXCVBNM"
    for i in name:
        if i in symbol:
           x += 1
    if x > 0: return True
    if x == 0: return False 
    
    
def Fnames(First): 
    BF = isAlph(First)
    if len(First) > 1 and BF: 
        return True 

def Lnames(Last): 
    BL = isAlph(Last)
    if len(Last) > 1 and BL: 
        return True 
       
def ZIP(Zip):
    if isNum(Zip):
        return True 

def EmpID(ID):
    if isAlph(ID[0:2]) and ID[2] == '-' and isNum(ID[3:5]):
        return True 

First = input("Please enter your first name? ")
Last = input("Please enter your last name? ")
Zip = input("Please enter your zip code? ")
ID = input("Please enter your ID? ")

if Fnames(First) != True: print(f"{First} is not a name. It is too short.")
if Lnames(Last) != True: print(f"{Last} is not a name. It is too short. ")
if ZIP(Zip) != True: print("The Zip is not a numeric number")
if EmpID(ID) != True: print(f"{ID} is not a valid ID")

Please enter your first name? j
Please enter your last name? m
Please enter your zip code? j
Please enter your ID? j
j is not a name. It is too short.
m is not a name. It is too short. 
The Zip is not a numeric number


IndexError: string index out of range

In [36]:
#27:
def validation():
    f_name=input("Enter first name")
    s_name=input("Enter second name")
    if len(f_name)>2 and len(s_name)>2:
        try:
            float(input("ZIP?"))
        except ValueError:
            print("Invalid ZIP")
        finally:
            q=(input("ID"))
            if q[0:2].isalpha()==True and q[2]=="-" and q[3:].isalnum()==True:
                print("There are no errors")
            else:
                print("There are errors")
    else:
        print("First and second numbers must be >2")
                       
                   
            
            

In [1]:
#27:
def validation():
    f_name=input("Enter first name")
    s_name=input("Enter second name")
    if len(f_name)>2 and len(s_name)>2:
        try:
            float(input("ZIP?"))
            q=(input("ID"))
            if q[0:2].isalpha()==True and q[2]=="-" and q[3:].isalnum()==True:
                print("There are no errors")
            else:
                print("There are errors")
        except ValueError:
            print("Invalid ZIP")
    else:
        print("First and second numbers must be >2")

In [3]:
validation()

Enter first namejuan
Enter second namepalomo
ZIP?1234
IDaa-49222
There are no errors


In [16]:
#28
i=0
q=[]
while i<5:
    try:
        one=float(input("Enter a number  "))
        q.append(one)
        i+=1
        if i==5:
            print(f'The total is {sum(q[:])}')
    except ValueError:
        print("Please enter a number")

Enter a number  a
Please enter a number
Enter a number  a
Please enter a number
Enter a number  a
Please enter a number
Enter a number  b
Please enter a number
Enter a number  1
Enter a number  2
Enter a number  3
Enter a number  4
Enter a number  5
The total is 15.0


In [28]:
#29
def calc_72():
    while True:
        try:
            r=float(input("What is the rate of return?  "))
            years=72/r
            print(f'It will take {round(years,1)} years to double\nyour initial investment')
            break
        except (ValueError, ZeroDivisionError):
            print("Sorry, that is not a valid input")

In [30]:
calc_72()

What is the rate of return?  33
It will take 2.2 years to double
your initial investment


In [1]:
#30
import numpy as np
m=np.zeros((13,13))
x=np.arange(0,13)
for i in range(0,13):
    m[i,:]=x*i
    print(m[i,:])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24.]
[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27. 30. 33. 36.]
[ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36. 40. 44. 48.]
[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60.]
[ 0.  6. 12. 18. 24. 30. 36. 42. 48. 54. 60. 66. 72.]
[ 0.  7. 14. 21. 28. 35. 42. 49. 56. 63. 70. 77. 84.]
[ 0.  8. 16. 24. 32. 40. 48. 56. 64. 72. 80. 88. 96.]
[  0.   9.  18.  27.  36.  45.  54.  63.  72.  81.  90.  99. 108.]
[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100. 110. 120.]
[  0.  11.  22.  33.  44.  55.  66.  77.  88.  99. 110. 121. 132.]
[  0.  12.  24.  36.  48.  60.  72.  84.  96. 108. 120. 132. 144.]


In [1]:
#31
import prettytable
def target_heart_rate():
    while True:
        try:
            t = prettytable.PrettyTable(['Intensity', 'Rate'])
            rHR=float(input("Resting pulse?  "))
            age=float(input("Age?  "))
            i=55
            while i<100:
                formulae=(((220-age)-rHR)*(i/100))+rHR
                t.add_row([f'{i}%', f'{int(formulae)} bpm'])
                i+=5
            print(t)
            break
        except ValueError:
            print("Please enter the data in numbers")

In [30]:
target_heart_rate()

Resting pulse?  a
Please enter the data in numbers
Resting pulse?  a
Please enter the data in numbers
Resting pulse?  65
Age?  22
+-----------+---------+
| Intensity |   Rate  |
+-----------+---------+
|    55%    | 138 bpm |
|    60%    | 144 bpm |
|    65%    | 151 bpm |
|    70%    | 158 bpm |
|    75%    | 164 bpm |
|    80%    | 171 bpm |
|    85%    | 178 bpm |
|    90%    | 184 bpm |
|    95%    | 191 bpm |
+-----------+---------+


In [34]:
#palindrome para noobs
def isPalindrome1(s):
    if len(s)<=1:
        return True
    else:
        if s[0]==s[-1] and isPalindrome(s[1:-1]):
            return True
        else:
            return False

In [35]:
isPalindrome("abcsjba")

False

In [36]:
#palindrome para pros
def isPalindrome(s):
    if len(s)<=1:
        return True
    else:
        return s[0]==s[-1] and isPalindrome(s[1:-1])

In [37]:
isPalindrome("abcba")

True

In [9]:
import random
random.randint(1,2)

2

In [20]:
#05-05-20
#32

x=True
while x==True:
    play=int(input("Let's play Guess the Number!\nPick a difficulty level (1 or 2):"))
    if play==1:
        random_1=random.randint(1,10)
        play_1=int(input("I have my number. What's your guess?"))
        if random_1==play_1:
            print("You guessed it!")
        elif random_1!=play_1:
            n=1
            while True:
                if random_1>play_1:
                    play_1=int(input("Too low! Guess again"))
                    n+=1
                elif random_1<play_1:
                    play_1=int(input("Too high! Guess again"))
                    n+=1
                elif random_1==play_1:
                    print(f'You got it in {n} guesses!')
                    break
    elif play==2:
        random_1=random.randint(1,100)
        play_1=int(input("I have my number. What's your guess?"))
        if random_1==play_1:
            print("You guessed it!")
        elif random_1!=play_1:
            n=1
            while True:
                if random_1>play_1:
                    play_1=int(input("Too low! Guess again"))
                    n+=1
                elif random_1<play_1:
                    play_1=int(input("Too high! Guess again"))
                    n+=1
                elif random_1==play_1:
                    print(f'You got it in {n} guesses!')
                    break
    finish=bool(input("Play again?"))
    if finish==False:
        x=False


Let's play Guess the Number!
Pick a difficulty level (1 or 2):2
I have my number. What's your guess?100
Too high! Guess again10
Too low! Guess again50
Too low! Guess again60
Too low! Guess again70
Too high! Guess again65
Too high! Guess again64
You got it in 7 guesses!
Play again?


In [10]:
#33
def eight_ball():
    answers=["Yes","No","Maybe","Ask again later"]
    input("What's your question?  ")
    print(random.choice(answers))

In [11]:
eight_ball()

What's your question?  s&p up?
No


In [12]:
#34

emp=[]
while True:
    print(f'There are {len(emp)} employees:')
    for i in emp:
        print(i)
    x=input("Insert or remove ")
    if x=="insert":
        y=input("Name? ")
        emp.append(y)
    elif x=="remove":
        y=input("Name? ")
        emp.remove(y)

There are 0 employees:


KeyboardInterrupt: 

In [6]:
#35
z=[]
x=True
import random
while x==True:
    y=input("Enter a name: ")
    if y!="":
        z.append(y)
    elif y=="":
        print(f'The winner is... {random.choice(z)}')
        x=False
    

Enter a name: J
Enter a name: A
Enter a name: S
Enter a name: 
The winner is... S


In [47]:
#36
import statistics
arr=[]
x=True
while x==True:
    numbers=input("Enter a number: ")
    try:
        if numbers!="done":
            arr.append(float(numbers))
        elif numbers=="done":
            print(f'{arr}\nThe average is {np.mean(arr)}.\nThe minimum is {np.min(arr)}.\nThe maximum is {np.max(arr)}.\nThe standard deviation is {np.std(arr)}.')
            x=False
    except ValueError:
        print("Please enter a number, or 'done' if you finished")
        x=True

Enter a number: 
Please enter a number, or 'done' if you finished
Enter a number: done
Please enter a number, or 'done' if you finished
Enter a number: 1
Enter a number: 2
Enter a number: done
[1.0, 2.0]
The average is 1.5.
The minimum is 1.0.
The maximum is 2.0.
The standard deviation is 0.5.


In [30]:
import numpy as np

In [42]:
#37

import random
import string

def random_password():
    special=["!","·","$","%","&","@","/","*"]

    l=int(input("What's the minimum length?: "))


    s=int(input("How many special characters?: "))

    s_1=random.sample(special, s)

    n=int(input("How many numbers?: "))
    n_1=random.sample(range(10),n)

    l_1=random.sample(string.ascii_lowercase,l-s-n)

    passw=s_1+n_1+l_1
    random.shuffle(passw)
    print("Your password is:")
    print(*passw,sep="")


In [43]:
random_password()

What's the minimum length?: 20
How many special characters?: 5
How many numbers?: 5
Your password is:
o7fxg0e·wzt2%4k/l3&@


In [63]:
#38
n = input("Enter a list of numbers, separated by space:")
l=n.split()
l_1 = []
for i in l:
    if float(i)%2==0:
        l_1.append(i)


print("The even numbers are:",*l_1)


        

Enter a list of numbers, separated by space:3 4 5 7 8 
The even numbers are: 4 8


In [33]:
import prettytable

t = prettytable.PrettyTable(['Name', 'Position', 'Separation Date'])
q=[]
x=True
while x==True:
        inp=input("First and Last Name, Position and Date")
        if inp is not "":
            q.append(inp.split(","))
            print(q)
        else:
            x=False
            q.sort()
            for i in q: 
                a=i[0]
                b=i[1]
                c=i[2]
                t.add_row([a, b, c])
print(t)
            



First and Last Name, Position and Datejuan,ceo,12
[['juan', 'ceo', '12']]
First and Last Name, Position and Datemaria,cfo,10
[['juan', 'ceo', '12'], ['maria', 'cfo', '10']]
First and Last Name, Position and Date
+-------+----------+-----------------+
|  Name | Position | Separation Date |
+-------+----------+-----------------+
|  juan |   ceo    |        12       |
| maria |   cfo    |        10       |
+-------+----------+-----------------+


In [68]:
#41
op=open("untitled_2.txt")
e=[i.rstrip() for i in op]
sort=sorted(e)
t = prettytable.PrettyTable([f'Total of {len(sort)} names'])
for i in sort:
    t.add_row([i])
print(t)
op.close()

+-------------------+
|  Total of 7 names |
+-------------------+
|    Johnson, Jim   |
|    Jones, Aaron   |
|    Jones, Chris   |
|     Ling, Mai     |
|  Swift, Geoffrey  |
|    Xiong, Fong    |
| Zarnecki, Sabrina |
+-------------------+


In [78]:
import csv
t = prettytable.PrettyTable(['Last','First','Salary'])
with open('untitled_2.txt') as file:
    reader = csv.reader(file)
    for row in reader:
        t.add_row(row)
    print(t)
    file.close()

+----------+----------+--------+
|   Last   |  First   | Salary |
+----------+----------+--------+
|   Ling   |   Mai    | 55900  |
| Johnson  |   Jim    | 56500  |
|  Jones   |  Aaron   | 46000  |
|  Jones   |  Chris   | 34500  |
|  Swift   | Geoffrey | 14200  |
|  Xiong   |   Fong   | 65000  |
| Zarnecki | Sabrina  | 51500  |
+----------+----------+--------+


In [4]:
#43
import os
path = os.getcwd()
print ("The current working directory is %s" % path)

The current working directory is /Users/JulioMF/Desktop/programming/Python/exercises_for_programmers_book


In [11]:
name = input("Enter the name of the site: ")
auth = input("Enter the name of the author: ")
java = bool(input("JavaScript folder? "))
css = bool(input("CSS folder? "))

try:
    os.mkdir(name)
except OSError:
    print ("Creation of the directory %s failed" % path)
else:
    print ("Successfully created the directory %s " % path)
if java==True:
    try:
        os.mkdir("js")
    except OSError:
        print ("Creation of the directory failed js")
    else:
        print ("Successfully created the directory js")
if css==True:
    try:
        os.mkdir("css")
    except OSError:
        print ("Creation of the directory failed css")
    else:
        print ("Successfully created the directory css")

Enter the name of the site: keepithuman
Enter the name of the author: Ricardo Climent
JavaScript folder? y
CSS folder? y
Successfully created the directory /Users/JulioMF/Desktop/programming/Python/exercises_for_programmers_book 
Successfully created the directory js
Successfully created the directory css


In [9]:
print(java)

True


In [1]:
#44
def data_base():
    n="name"
    p="price"
    q="quantity"
    search=input("What is the product name? ")
    products=[{n:"iPad",p:25,q:5},
             {n:"iPhone",p:50,q:2},
             {n:"Mac",p:75,q:7}]
    for i in products:
        if search in i.values():
            product=i
            for a,b in i.items():
                print(f'{a.upper()}: {b}')
    y_or_no=bool(input("Would you like to buy it? "))
    if y_or_no==True:
        i[q]-=1
        print(f'Thank you! Bill: {i[p]}€')


What is the product name? Mac
NAME: Mac
PRICE: 75
QUANTITY: 7
Would you like to buy it? y
Thank you! CF=+75
